# Generated by Django 5.0.1 on 2024-01-15 21:28

import datetime
import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('str_image', models.CharField()),
                ('value', models.CharField()),
            ],
            options={
                'verbose_name': 'контакт',
                'verbose_name_plural': 'контакты',
                'db_table': 'contact',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Название')),
                ('url', models.CharField(verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'меню',
                'db_table': 'menu',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Товар')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('title', models.CharField(verbose_name='Название')),
                ('description', models.CharField(default='...', verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
                'db_table': 'product',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(verbose_name='Номер заказа')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='RU', verbose_name='Телефон')),
                ('bot_shop', models.IntegerField(verbose_name='Бот-магазин')),
                ('admin_panel', models.IntegerField(verbose_name='Админ-панель')),
                ('database', models.IntegerField(verbose_name='База данных')),
                ('total_price', models.IntegerField(verbose_name='Общая цена')),
                ('date', models.DateTimeField(default=datetime.datetime.utcnow, verbose_name='Дата')),
                ('status', models.CharField(choices=[('В работе', 'В работе'), ('Оформлен', 'Оформлен'), ('Исполнен', 'Исполнен')], default='Оформлен', verbose_name='Статус')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
                'db_table': 'order',
                'ordering': ['-date'],
            },
        ),
    ]
